### ISSUE TITLE
GWLB 6.4 PAYG - fails if 0.0.0.0/0 used as PublicDefaultRouteSPK*

### ISSUE THREAD

**Issue by wintermute000** [40net-cloud/fortinet-aws-solutions#6]
For the template https://github.com/40net-cloud/fortinet-aws-solutions/tree/master/FortiGate/GWLB/6.4/PAYG

Stack creation consistently fails with 
VPCRouteSPK1	CREATE_FAILED	The route identified by 0.0.0.0/0 already exists
VPCRouteSPK2	CREATE_FAILED	The route identified by 0.0.0.0/0 already exists

I figured out eventually that the stack doesn't like you using 0.0.0.0/0 as your source IP because then it dupes 0.0.0.0/0 here

```
  PublicDefaultRouteSPK1:
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: !Ref MyIPForAccess
      GatewayId: !Ref IGWSPK
      RouteTableId: !Ref RouteTableSPK1PUB
    Type: 'AWS::EC2::Route'
```

and

```
   VPCRouteSPK1:
    Type: 'AWS::EC2::Route'
    DependsOn: TgwAttSPK1
    Properties:
      RouteTableId: !Ref RouteTableSPK1PUB
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref TGW1
```

I tried deleting the VPCRouteSPK1 / 2 resources but the the init function starts failing so I put a /32 in there as per example. 

Suggest putting warning in docs
